name: Test triggring workflow
on: 
   workflow_dispatch:
    
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - run: |
         curl \
         -X POST https://api.github.com/repos/IvanZosimov/TestRepo/dispatches \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: $PAT"\
         -H "X-GitHub-Api-Version: 2022-11-28" \
         -d '{"event_type":"test","client_payload":{"unit":false,"integration":true}}'
      env:
         PAT: ${{ secrets.PAT }}
