name: Test triggring workflow
on:
   push:
      paths:
         - "./{.eslintrc,.prettierrc}.json"
   workflow_dispatch:
    
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - run: |
         curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/IvanZosimov/TestRepo/dispatches \
           -d '{"event_type":"test"}'
         
         
      env:
         PAT: ${{ secrets.PAT }}
