name: Test triggring workflow
on: 
   workflow_dispatch:
    
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - run: |
         curl --version
         curl \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -u "IvanZosimov:${{ secrets.PAT }}"
         -H "Authorization: ${{ secrets.PAT }}"\
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/IvanZosimov/TestRepo \
         -d '{"event_type":"test","client_payload":{"unit":false,"integration":true}}'
         
         
      env:
         PAT: ${{ secrets.PAT }}
