# Definition

name: Update tools configurations

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses. Defaults to ['ubuntu-latest', 'windows-latest', 'macos-latest'] if not set"
        required: false
        type: string
        default: "['ubuntu-latest', 'windows-latest', 'macos-latest']"

jobs:
  update-tools-configurations:
  runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with:
        path: 'current'
        
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'IvanZosimov/reusable-workflows-fork'
        path: 'example'

    - name: Configure git service account
      run: |       
        git config --global user.name 'Service account'
        git config --global user.email 'no-reply@microsoft.com'
    - name: Update configuration files
      run: |       
        
        cd "./current"
        git checkout -b update-tool-config
        cp -f  "${{github.workspace}}/example/.eslintrc.json" "${{github.workspace}}/current/"
        cp -f  "${{github.workspace}}/example/.prettierrc.json" "${{github.workspace}}/current/"
        
    - name: Create commit and push changes
      id: successful-commit
      run: |     
        
        cd "./current"
        git add .
        if git commit -m "Update tool configuration files"; then
            git push origin update-tool-config -f
            echo "STATUS=true" >> $GITHUB_OUTPUT
        else
        
            echo "::notice title=Workflow notice::No updates were found in the example repo."
            echo "STATUS=false" >> $GITHUB_OUTPUT
        fi     
    
    - name: Create pull request
      if: ${{ steps.successful-commit.outputs.STATUS == 'true' }}
      run: |
         curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/pulls \
          -d '{"title":"'"ESLinter/Prettier configurations update from $(date +'%m/%d/%Y')"'","body":"In the scope of this PR ESLint or Prettier configuration files should be updated to match with example configuration files stored in '"[reusable-workflows](https://github.com/actions/reusable-workflows)"' repository.","head":"update-tool-config-branch","base":"main"}'
        
        
